export type ItemMasterRecord = {
  sku: string;
  name: string;
  category: string;
  unitCost: string;
  uom: string;
  stock: string;
  reorder: string;
  vendor: string;
  status: string;
  hasTransactions: boolean;
};

export const itemMaster: ItemMasterRecord[] = [
  {
    sku: "SFG-SLK-NTW-30D-HNK",
    name: "HANK WINDED SILK 30 DENIER",
    category: "Semi-finished goods",
    unitCost: "₹185.00",
    uom: "kg",
    stock: "320",
    reorder: "250",
    vendor: "SilkWorks Co.",
    status: "Active",
    hasTransactions: false,
  },
  {
    sku: "SFG-SLK-NTW-30D-SOK",
    name: "SOAKED SILK 30 DENIER",
    category: "Semi-finished goods",
    unitCost: "₹178.50",
    uom: "kg",
    stock: "275",
    reorder: "220",
    vendor: "SilkWorks Co.",
    status: "Active",
    hasTransactions: false,
  },
  {
    sku: "SFG-SLK-STW-30D-2PLY-ASW",
    name: "ASSEMBLY WINDED 2 PLY SILK 30 DENIER (S)",
    category: "Semi-finished goods",
    unitCost: "₹192.40",
    uom: "kg",
    stock: "210",
    reorder: "180",
    vendor: "SeriTex Assemblies",
    status: "Active",
    hasTransactions: true,
  },
  {
    sku: "SFG-SLK-STW-30D-2PLY-TPI13-TFOP",
    name: "PRIMARY TWISTING 2 PLY SILK 30 DENIER (S) - 13 TPI",
    category: "Semi-finished goods",
    unitCost: "₹198.75",
    uom: "kg",
    stock: "165",
    reorder: "150",
    vendor: "SeriTex Assemblies",
    status: "Active",
    hasTransactions: true,
  },
  {
    sku: "SFG-SLK-STW-30D-2PLY-TPI55-PW",
    name: "PIRN WINDED 2 PLY (S) 30 DENIER SILK-55 TPI",
    category: "Semi-finished goods",
    unitCost: "₹204.60",
    uom: "kg",
    stock: "140",
    reorder: "160",
    vendor: "SeriTex Assemblies",
    status: "Reorder",
    hasTransactions: true,
  },
  {
    sku: "SFG-SLK-STW-30D-2PLY-TPI55-RW",
    name: "REWINDED 2 PLY (S) 30 DENIER SILK-55 TPI",
    category: "Semi-finished goods",
    unitCost: "₹206.10",
    uom: "kg",
    stock: "190",
    reorder: "170",
    vendor: "SeriTex Assemblies",
    status: "Active",
    hasTransactions: true,
  },
  {
    sku: "SFG-SLK-STW-30D-2PLY-TPI55-TFOS",
    name: "TWISTING SECONDARY 2 PLY (S) 30 DENIER SILK-55 TPI",
    category: "Semi-finished goods",
    unitCost: "₹209.20",
    uom: "kg",
    stock: "155",
    reorder: "140",
    vendor: "SeriTex Assemblies",
    status: "Active",
    hasTransactions: true,
  },
  {
    sku: "SFG-SLK-STW-30D-2PLY-TPI55-VHS",
    name: "VACUUM HEAT SETTING 2 PLY (S) 30 DENIER SILK-55 TPI",
    category: "Semi-finished goods",
    unitCost: "₹212.00",
    uom: "kg",
    stock: "125",
    reorder: "150",
    vendor: "SeriTex Assemblies",
    status: "Reorder",
    hasTransactions: true,
  },
  {
    sku: "SFG-SLK-STW-30D-HNK",
    name: "HANK WINDED SILK 30 DENIER (S)",
    category: "Semi-finished goods",
    unitCost: "₹188.30",
    uom: "kg",
    stock: "240",
    reorder: "200",
    vendor: "SilkWorks Co.",
    status: "Active",
    hasTransactions: false,
  },
  {
    sku: "SFG-SLK-STW-30D-SOK",
    name: "SOAKED SILK 30 DENIER (S)",
    category: "Semi-finished goods",
    unitCost: "₹182.60",
    uom: "kg",
    stock: "205",
    reorder: "180",
    vendor: "SilkWorks Co.",
    status: "Active",
    hasTransactions: false,
  },
  {
    sku: "SFG-SLK-SZTW-30D-5440-SWRP",
    name: "GEORGETTE 80 GMS SILK WARP 5440 ENDS",
    category: "Semi-finished goods",
    unitCost: "₹228.40",
    uom: "kg",
    stock: "110",
    reorder: "120",
    vendor: "WarpTex",
    status: "Watch",
    hasTransactions: true,
  },
  {
    sku: "SFG-SLK-ZTW-30D-2PLY-ASW",
    name: "ASSEMBLY WINDED 2 PLY SILK 30 DENIER (Z)",
    category: "Semi-finished goods",
    unitCost: "₹193.90",
    uom: "kg",
    stock: "215",
    reorder: "190",
    vendor: "SeriTex Assemblies",
    status: "Active",
    hasTransactions: true,
  },
  {
    sku: "SFG-SLK-ZTW-30D-2PLY-TPI13-TFOP",
    name: "PRIMARY TWISTING 2 PLY SILK 30 DENIER (Z) - 13 TPI",
    category: "Semi-finished goods",
    unitCost: "₹199.60",
    uom: "kg",
    stock: "160",
    reorder: "150",
    vendor: "SeriTex Assemblies",
    status: "Active",
    hasTransactions: true,
  },
  {
    sku: "SFG-SLK-ZTW-30D-2PLY-TPI55-PW",
    name: "PIRN WINDED 2 PLY (Z) 30 DENIER SILK-55 TPI",
    category: "Semi-finished goods",
    unitCost: "₹205.20",
    uom: "kg",
    stock: "145",
    reorder: "160",
    vendor: "SeriTex Assemblies",
    status: "Reorder",
    hasTransactions: true,
  },
  {
    sku: "SFG-SLK-ZTW-30D-2PLY-TPI55-RW",
    name: "REWINDED 2 PLY (Z) 30 DENIER SILK-55 TPI",
    category: "Semi-finished goods",
    unitCost: "₹206.60",
    uom: "kg",
    stock: "175",
    reorder: "170",
    vendor: "SeriTex Assemblies",
    status: "Active",
    hasTransactions: true,
  },
  {
    sku: "SFG-SLK-ZTW-30D-2PLY-TPI55-TFOS",
    name: "TWISTING SECONDARY 2 PLY (Z) 30 DENIER SILK-55 TPI",
    category: "Semi-finished goods",
    unitCost: "₹210.30",
    uom: "kg",
    stock: "150",
    reorder: "140",
    vendor: "SeriTex Assemblies",
    status: "Active",
    hasTransactions: true,
  },
  {
    sku: "SFG-SLK-ZTW-30D-2PLY-TPI55-VHS",
    name: "VACUUM HEAT SETTING 2 PLY (Z) 30 DENIER SILK-55 TPI",
    category: "Semi-finished goods",
    unitCost: "₹213.10",
    uom: "kg",
    stock: "130",
    reorder: "140",
    vendor: "SeriTex Assemblies",
    status: "Watch",
    hasTransactions: true,
  },
  {
    sku: "SFG-SLK-ZTW-30D-HNK",
    name: "HANK WINDED SILK 30 DENIER (Z)",
    category: "Semi-finished goods",
    unitCost: "₹189.80",
    uom: "kg",
    stock: "230",
    reorder: "200",
    vendor: "SilkWorks Co.",
    status: "Active",
    hasTransactions: false,
  },
];
